### ISSUE TITLE
Natural conclusion

### ISSUE THREAD

**Issue by RogueScholar** [hnarayanan/springer-books#6]
Since Springer has reached the limits of their capitalistic generosity (can't bear to miss out on a whole new crop of already-terrified and ultra-compliant COVID freshmen, I presume) and [ended the offer of free downloads](https://www.springernature.com/gp/librarians/the-link/blog/blogposts-ebooks/free-access-to-a-range-of-essential-textbooks/17855960) to any of these titles on the final day of last month, perhaps it's time to either update the lede to say as much or sunset the page altogether. I took the liberty of [triggering one more scrape](https://web.archive.org/web/20200812225439/https://hnarayanan.github.io/springer-books/) of it into the Wayback Machine just a few seconds ago to make sure its existence was never truly forgotten, for what it's worth.

More pressingly I wanted to take a moment to thank you for assembling the page in the first place. It was a marvelously helpful improvement and act of beneficence built upon one of the few good things to arise from this pandemic. The people I know through open-source projects are consistently the source of most of my (admitted rather skeptical) optimism about humanity's long-term outlook and this effort of yours is an exquisite example why. My hat's off to you and I hope you and your family have been and will remain well throughout this crisis.

**Comment by hnarayanan** [comment]
Thanks! It was even more complicated.

My wife of ten years told me she wanted out just at the start of the pandemic, so working on projects like this helped me stay sane in these unfortunate times.

I will update the lead copy.
